### ISSUE TITLE
non-prototype methods not documented properly

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#40]
See dojo/Declare.js.   It declares methods from the constructor rather than in a prototype:

``` javascript
this.progress = function(update, /*Boolean?*/ strict){
    // summary:
    //      Emit a progress update on the deferred.
    // returns: dojo/promise/Promise
    //      Returns the original promise for the deferred.
    //
    // update:
    //      The progress update
    // strict:
    //      If strict, will throw an error if the deferred is already fulfilled.
    if(!fulfilled){
...
```

None of that information is showing up in the API output, it just has

``` xml
<method name="progress" scope="prototype" type="function" from="dojo/Deferred">
<parameters/>
<return-types/>
</method>
```

**Comment by wkeese** [comment]
@cc novemberborn

**Comment by csnover** [comment]
The way that `dojo/Deferred.js` is written is bizarre so I am not sure if this can be considered a parser bug or simply a limitation of the way the static analysis is currently performed.

What’s happening here is that the constructor function is evaluated first, which means all the functions in the constructor are added as members of the prototype of the constructor…then the defined prototype object is mixed in by `lang.extend` but, it’s full of empty functions that overwrite the ones that were added during analysis of the constructor.

This works since at runtime the constructor function resets the instance’s properties, but because of the way the parser works right now, it breaks.

There are a few potential avenues for solving this:
1. Put instance variables on a different property of the generated Value instead of adding them to the `prototype` property
2. Update the `lang.extend` call handler to not override prototypes that already exist
3. Modify `dojo/Deferred.js` to have the code comments on the prototype object instead of in the constructor.

The first might be the most correct in the long term, but I am leaning toward the third option for now.

**Comment by wkeese** [comment]
Oh I didn't notice that strange stub prototype before, but now I see it:

``` javascript
 {
    // Define the shape of Deferred instances
    promise: null,
    resolve: noop,
    reject: noop,
    progress: noop,
    then: noop,
    cancel: noop,
    isResolved: noop,
    isRejected: noop,
    isFulfilled: noop,
    isCanceled: noop
});
```

I don't understand why that is there.

I agree that moving the method descriptions to the prototype (while leaving the implementations where they are) would solve the problem.    (Alternately just removing that prototype completely would solve the problem, but presumably it's there for some reason.)

@novemberborn - any comments??

**Comment by novemberborn** [comment]
The thinking was that defining those methods on the prototype would help engines predict the shape of the object — admittedly I don't understand enough of engine internals no know whether that really helps.

Simplest thing would be to just remove the prototype. Yay or nay?

**Comment by wkeese** [comment]
Oh we can just remove it?    Great.   I confirmed that removing the prototype makes the method descriptions show up in the doc.    There's one doc parser bug: I can't set a description on the promise property.   But that's relatively minor.

I'll update Deferred.js.
